# Generated by Django 2.1.7 on 2021-08-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.FloatField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
